backend:
  name: git-gateway

media_folder: static/images
public_folder: /images

collections:
- name: blog
  label: Blog
  folder: content/en/blog/_posts
  create: true
  fields:
  - {label: Title, name: title, widget: string}
  - {label: Draft, name: draft, widget: string, default: true}
  - {label: Body, name: body, widget: markdown}
